export const LOAD_DRIVERS_REQUEST = 'LOAD_DRIVERS_REQUEST';
export const LOAD_DRIVERS_SUCCESS = 'LOAD_DRIVERS_SUCCESS';
export const LOAD_DRIVERS_ERROR = 'LOAD_DRIVERS_ERROR';

export const LOAD_DRIVER_DETAIL_REQUEST = 'LOAD_DRIVER_DETAIL_REQUEST';
export const LOAD_DRIVER_DETAIL_SUCCESS = 'LOAD_DRIVER_DETAIL_SUCCESS';
export const LOAD_DRIVER_DETAIL_ERROR = 'LOAD_DRIVER_DETAIL_ERROR';
